// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: accessControl.proto

package accessControl;

public final class accessControlImpl {
  private accessControlImpl() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_accessControl_LoginRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_accessControl_LoginRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_accessControl_LoginResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_accessControl_LoginResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_accessControl_AuthorizationRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_accessControl_AuthorizationRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_accessControl_AuthorizationResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_accessControl_AuthorizationResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_accessControl_LogoutRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_accessControl_LogoutRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_accessControl_LogoutResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_accessControl_LogoutResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_accessControl_ErrorResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_accessControl_ErrorResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_accessControl_Empty_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_accessControl_Empty_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\023accessControl.proto\022\raccessControl\"2\n\014" +
      "LoginRequest\022\020\n\010username\030\001 \001(\t\022\020\n\010passwo" +
      "rd\030\002 \001(\t\">\n\rLoginResponse\022\027\n\017responseMes" +
      "sage\030\001 \001(\t\022\024\n\014responseCode\030\002 \001(\005\"$\n\024Auth" +
      "orizationRequest\022\014\n\004name\030\001 \001(\t\">\n\025Author" +
      "izationResponse\022\017\n\007message\030\001 \001(\t\022\024\n\014resp" +
      "onseCode\030\002 \001(\005\"!\n\rLogoutRequest\022\020\n\010usern" +
      "ame\030\001 \001(\t\"?\n\016LogoutResponse\022\027\n\017responseM" +
      "essage\030\001 \001(\t\022\024\n\014responseCode\030\002 \001(\005\"J\n\rEr" +
      "rorResponse\022\020\n\010username\030\001 \001(\t\022\020\n\010passwor" +
      "d\030\002 \001(\t\022\025\n\rexpectedValue\030\003 \001(\t\"\007\n\005Empty2" +
      "\376\001\n\raccessControl\022D\n\005login\022\033.accessContr" +
      "ol.LoginRequest\032\034.accessControl.LoginRes" +
      "ponse\"\000\022^\n\rauthorization\022#.accessControl" +
      ".AuthorizationRequest\032$.accessControl.Au" +
      "thorizationResponse\"\0000\001\022G\n\006logout\022\034.acce" +
      "ssControl.LogoutRequest\032\035.accessControl." +
      "LogoutResponse\"\000B$\n\raccessControlB\021acces" +
      "sControlImplP\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_accessControl_LoginRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_accessControl_LoginRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_accessControl_LoginRequest_descriptor,
        new java.lang.String[] { "Username", "Password", });
    internal_static_accessControl_LoginResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_accessControl_LoginResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_accessControl_LoginResponse_descriptor,
        new java.lang.String[] { "ResponseMessage", "ResponseCode", });
    internal_static_accessControl_AuthorizationRequest_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_accessControl_AuthorizationRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_accessControl_AuthorizationRequest_descriptor,
        new java.lang.String[] { "Name", });
    internal_static_accessControl_AuthorizationResponse_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_accessControl_AuthorizationResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_accessControl_AuthorizationResponse_descriptor,
        new java.lang.String[] { "Message", "ResponseCode", });
    internal_static_accessControl_LogoutRequest_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_accessControl_LogoutRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_accessControl_LogoutRequest_descriptor,
        new java.lang.String[] { "Username", });
    internal_static_accessControl_LogoutResponse_descriptor =
      getDescriptor().getMessageTypes().get(5);
    internal_static_accessControl_LogoutResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_accessControl_LogoutResponse_descriptor,
        new java.lang.String[] { "ResponseMessage", "ResponseCode", });
    internal_static_accessControl_ErrorResponse_descriptor =
      getDescriptor().getMessageTypes().get(6);
    internal_static_accessControl_ErrorResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_accessControl_ErrorResponse_descriptor,
        new java.lang.String[] { "Username", "Password", "ExpectedValue", });
    internal_static_accessControl_Empty_descriptor =
      getDescriptor().getMessageTypes().get(7);
    internal_static_accessControl_Empty_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_accessControl_Empty_descriptor,
        new java.lang.String[] { });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
