// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: accessControl.proto

package accessControl;

public interface EmptyOrBuilder extends
    // @@protoc_insertion_point(interface_extends:accessControl.Empty)
    com.google.protobuf.MessageOrBuilder {
}
