// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: accessControl.proto

package accessControl;

public interface ErrorResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:accessControl.ErrorResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string username = 1;</code>
   */
  java.lang.String getUsername();
  /**
   * <code>string username = 1;</code>
   */
  com.google.protobuf.ByteString
      getUsernameBytes();

  /**
   * <code>string password = 2;</code>
   */
  java.lang.String getPassword();
  /**
   * <code>string password = 2;</code>
   */
  com.google.protobuf.ByteString
      getPasswordBytes();

  /**
   * <code>string expectedValue = 3;</code>
   */
  java.lang.String getExpectedValue();
  /**
   * <code>string expectedValue = 3;</code>
   */
  com.google.protobuf.ByteString
      getExpectedValueBytes();
}
