// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: lightingControl.proto

package lightingControl;

public interface EmptyOrBuilder extends
    // @@protoc_insertion_point(interface_extends:lightingControl.Empty)
    com.google.protobuf.MessageOrBuilder {
}
