// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: lightingControl.proto

package lightingControl;

public interface IntensityRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:lightingControl.IntensityRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 requestCode = 1;</code>
   */
  int getRequestCode();
}
