// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: lightingControl.proto

package lightingControl;

public final class lightingControlImpl {
  private lightingControlImpl() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_lightingControl_LoginRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_lightingControl_LoginRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_lightingControl_LoginResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_lightingControl_LoginResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_lightingControl_IntensityRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_lightingControl_IntensityRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_lightingControl_IntensityResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_lightingControl_IntensityResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_lightingControl_LogoutRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_lightingControl_LogoutRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_lightingControl_LogoutResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_lightingControl_LogoutResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_lightingControl_ErrorResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_lightingControl_ErrorResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_lightingControl_Empty_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_lightingControl_Empty_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\025lightingControl.proto\022\017lightingControl" +
      "\"2\n\014LoginRequest\022\020\n\010username\030\001 \001(\t\022\020\n\010pa" +
      "ssword\030\002 \001(\t\">\n\rLoginResponse\022\027\n\017respons" +
      "eMessage\030\001 \001(\t\022\024\n\014responseCode\030\002 \001(\005\"\'\n\020" +
      "IntensityRequest\022\023\n\013requestCode\030\001 \001(\005\"B\n" +
      "\021IntensityResponse\022\027\n\017responseMessage\030\001 " +
      "\001(\t\022\024\n\014responseCode\030\002 \001(\005\"!\n\rLogoutReque" +
      "st\022\020\n\010username\030\001 \001(\t\"?\n\016LogoutResponse\022\027" +
      "\n\017responseMessage\030\001 \001(\t\022\024\n\014responseCode\030" +
      "\002 \001(\005\"J\n\rErrorResponse\022\020\n\010username\030\001 \001(\t" +
      "\022\020\n\010password\030\002 \001(\t\022\025\n\rexpectedValue\030\003 \001(" +
      "\t\"\007\n\005Empty2\203\002\n\017lightingControl\022H\n\005login\022" +
      "\035.lightingControl.LoginRequest\032\036.lightin" +
      "gControl.LoginResponse\"\000\022Y\n\014setIntensity" +
      "\022!.lightingControl.IntensityRequest\032\".li" +
      "ghtingControl.IntensityResponse\"\000(\001\022K\n\006l" +
      "ogout\022\036.lightingControl.LogoutRequest\032\037." +
      "lightingControl.LogoutResponse\"\000B(\n\017ligh" +
      "tingControlB\023lightingControlImplP\001b\006prot" +
      "o3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_lightingControl_LoginRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_lightingControl_LoginRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_lightingControl_LoginRequest_descriptor,
        new java.lang.String[] { "Username", "Password", });
    internal_static_lightingControl_LoginResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_lightingControl_LoginResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_lightingControl_LoginResponse_descriptor,
        new java.lang.String[] { "ResponseMessage", "ResponseCode", });
    internal_static_lightingControl_IntensityRequest_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_lightingControl_IntensityRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_lightingControl_IntensityRequest_descriptor,
        new java.lang.String[] { "RequestCode", });
    internal_static_lightingControl_IntensityResponse_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_lightingControl_IntensityResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_lightingControl_IntensityResponse_descriptor,
        new java.lang.String[] { "ResponseMessage", "ResponseCode", });
    internal_static_lightingControl_LogoutRequest_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_lightingControl_LogoutRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_lightingControl_LogoutRequest_descriptor,
        new java.lang.String[] { "Username", });
    internal_static_lightingControl_LogoutResponse_descriptor =
      getDescriptor().getMessageTypes().get(5);
    internal_static_lightingControl_LogoutResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_lightingControl_LogoutResponse_descriptor,
        new java.lang.String[] { "ResponseMessage", "ResponseCode", });
    internal_static_lightingControl_ErrorResponse_descriptor =
      getDescriptor().getMessageTypes().get(6);
    internal_static_lightingControl_ErrorResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_lightingControl_ErrorResponse_descriptor,
        new java.lang.String[] { "Username", "Password", "ExpectedValue", });
    internal_static_lightingControl_Empty_descriptor =
      getDescriptor().getMessageTypes().get(7);
    internal_static_lightingControl_Empty_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_lightingControl_Empty_descriptor,
        new java.lang.String[] { });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
