// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: airConditionControl.proto

package airConditionControl;

public interface EmptyOrBuilder extends
    // @@protoc_insertion_point(interface_extends:airConditionControl.Empty)
    com.google.protobuf.MessageOrBuilder {
}
