// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: airConditionControl.proto

package airConditionControl;

public interface UpdateRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:airConditionControl.UpdateRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 requestCode = 1;</code>
   */
  int getRequestCode();
}
