// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: airConditionControl.proto

package airConditionControl;

public interface UpdateRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:airConditionControl.UpdateRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string requestMessage = 1;</code>
   */
  java.lang.String getRequestMessage();
  /**
   * <code>string requestMessage = 1;</code>
   */
  com.google.protobuf.ByteString
      getRequestMessageBytes();
}
